# Generated by Django 3.1.6 on 2021-04-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(1), related_name='categories', to='auctions.category'),
        ),
    ]
