# Generated by Django 3.1.6 on 2021-04-26 20:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210426_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 20, 28, 24, 889147, tzinfo=utc), verbose_name='comment date'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 20, 28, 24, 888151, tzinfo=utc), verbose_name='listing date'),
        ),
    ]
