# Generated by Django 3.1.6 on 2021-04-26 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210426_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='listing date'),
        ),
    ]
